// Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: 0BSD

plugins {
    id("com.github.jk1.dependency-license-report") version "2.9"
    id("de.undercouch.download") version "5.6.0"
}

licenseReport {
    outputDir = layout.buildDirectory.dir("reports/license").get().asFile.absolutePath
    renderers = arrayOf(
        com.github.jk1.license.render.InventoryReportRenderer("NOTICES")
    )
}

// Task to move the NOTICES file only into the root directory avoiding the intermediate jars report generated by the plugin
tasks.register<Copy>("generateNotices") {
    dependsOn("generateLicenseReport")
    from(layout.buildDirectory.dir("reports/license/NOTICES").get().asFile.absolutePath)
    into(rootDir.absolutePath)
}

repositories {
}

tasks.register<ConfigureProfilesTask>("configureProfiles") {
    group = "Custom"
    description = "Interactively configure development profiles."
}

