#!/bin/bash
# Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

set -eo pipefail

source /app/utils.sh


if [ "$TEST_MODE" == "on" ]; then
write_to_file "/integration-test/.generated.env" <<EOF
AUTH_MODE=${AUTH_MODE}
APP_PROVIDER_PARTY=${APP_PROVIDER_PARTY}
APP_USER_PARTY=${APP_USER_PARTY}
DSO_PARTY=${DSO_PARTY}
AUTH_APP_USER_WALLET_ADMIN_USER_NAME=${AUTH_APP_USER_WALLET_ADMIN_USER_NAME}
AUTH_APP_USER_WALLET_ADMIN_USER_PASSWORD=${AUTH_APP_USER_WALLET_ADMIN_USER_PASSWORD}
AUTH_APP_USER_WALLET_ADMIN_USER_ID=${AUTH_APP_USER_WALLET_ADMIN_USER_ID}
AUTH_APP_USER_AUTO_CONFIG_CLIENT_ID=${AUTH_APP_USER_AUTO_CONFIG_CLIENT_ID}
PARTICIPANT_JSON_API_PORT_SUFFIX=${PARTICIPANT_JSON_API_PORT_SUFFIX}
VALIDATOR_ADMIN_API_PORT_SUFFIX=${VALIDATOR_ADMIN_API_PORT_SUFFIX}
APP_USER_WALLET_ADMIN_TOKEN=${APP_USER_WALLET_ADMIN_TOKEN}
AUTH_APP_USER_TOKEN_URL=${AUTH_APP_USER_TOKEN_URL}
AUTH_APP_USER_VALIDATOR_CLIENT_SECRET=${AUTH_APP_USER_VALIDATOR_CLIENT_SECRET}
AUTH_APP_USER_VALIDATOR_CLIENT_ID=${AUTH_APP_USER_VALIDATOR_CLIENT_ID}
KEYCLOAK_BASE_URL=http://localhost:8082
EOF

else
  rm -f ./integration-test/.generated.env
fi
